# Generated by Django 4.1.7 on 2023-03-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsignage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slideshow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide_slideshow', to='digitalsignage.slideshow'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to='digitalsignage.slideshow'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='slideshow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slideshow', to='digitalsignage.slideshow'),
        ),
    ]
