# Generated by Django 4.1.7 on 2023-03-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsignage', '0002_slide_slideshow_alter_screen_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidetemplates',
            name='name',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
