# Generated by Django 4.1.7 on 2023-03-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsignage', '0003_slidetemplates_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
