# Generated by Django 4.1.7 on 2023-03-19 01:04

import digitalsignage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsignage', '0004_slide_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active_until',
            field=models.DateField(blank=True, default=digitalsignage.models.one_month_from_today, null=True),
        ),
    ]
