# Generated by Django 5.1.6 on 2025-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsignage', '0007_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbs'),
            preserve_default=False,
        ),
    ]
