# Generated by Django 5.1.8 on 2026-04-03 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsignage', '0008_asset_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
